import { Footer } from "@/components/navigation/Footer";
import { TopNavBar } from "@/components/navigation/TopNavBar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import theme from "../styles/muiTheme";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fubi Furniture",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <html lang="en">
    <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
        <body className={inter.className}>
          {/*Navbar*/}
          <TopNavBar />
          {children}
          <Footer />
        </body>
      </ThemeProvider>
    </AppRouterCacheProvider>
  </html>
);

export default RootLayout;
