import { Footer } from "./_components/navigation/Footer";
import { TopNavBar } from "./_components/navigation/Nav";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import theme from "./_styles/muiTheme";
import "./globals.css";
import Container from "@mui/material/Container";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fubi Furniture",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <html lang="en">
    <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
        <body className={inter.className}>
          <TopNavBar />
          <Container
            disableGutters={true}
            maxWidth={false}
            sx={{ display: "flex", flexDirection: "column", flex: 1 }}
          >
            {children}
          </Container>
          <Footer />
        </body>
      </ThemeProvider>
    </AppRouterCacheProvider>
  </html>
);

export default RootLayout;
